#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dataPath = path.join(root, "snippets/typst/data.json");
const outputPath = path.join(root, "snippets/hsnips/typst.hsnips");

const snippets = JSON.parse(fs.readFileSync(dataPath, "utf8"));

const header = `# Generated from snippets/typst/data.json.
# Run: node scripts/generate_typst_snippets.mjs
# Do not edit this file directly.
#
# HyperSnips expands automatic entries immediately. Manual entries marked
# "semicolon" also receive an automatic TRIGGER; variant. LuaSnip does not
# generate those variants: <Tab> expands the original manual trigger instead.
# Entries whose trigger itself contains ';' are manual under LuaSnip.

global
function math(context) {
  return context.scopes.some((scope) => scope.startsWith("markup.math.typst"));
}
endglobal
`;

function render(snippet, semicolon = false) {
  const trigger = snippet.trigger + (semicolon ? ";" : "");
  const description = snippet.description + (semicolon ? " (;)" : "");
  const automatic = semicolon || snippet.automatic;
  const flags = `${automatic ? "A" : ""}${semicolon || snippet.inWord ? "i" : "w"}`;
  const context = snippet.math ? "context math(context)\n" : "";
  const priority = semicolon && snippet.semicolonPriority
    ? `priority ${snippet.semicolonPriority}\n`
    : "";
  const resetPriority = priority ? "priority 0\n" : "";
  return `${priority}${context}snippet ${trigger} ${JSON.stringify(description)} ${flags}\n${snippet.body}\nendsnippet\n${resetPriority}`;
}

const regular = snippets.map((snippet) => render(snippet));
const variants = snippets.filter((snippet) => snippet.semicolon).map((snippet) => render(snippet, true));
const generated = `${header}\n${[...regular, ...variants].join("\n")}`;

if (process.argv.includes("--check")) {
  if (fs.readFileSync(outputPath, "utf8") !== generated) {
    console.error("snippets/hsnips/typst.hsnips is out of date");
    process.exit(1);
  }
} else {
  fs.writeFileSync(outputPath, generated);
}
